version: '3'

services:
  db:
    image: postgres:9.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - database-network
      - common-network
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - application-network
      - common-network
  
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - application-network

networks:
  application-network:
    driver: bridge
  database-network:
    driver: bridge
  common-network:
    driver: bridge
